---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
    application.properties: |
      quarkus.tls.trust-all=true
      quarkus.rest-client."org.acme.rest.client.ExtensionsService".url=http://rest-json-quickstart.default:8087/
      quarkus.opentelemetry.tracer.exporter.otlp.endpoint=http://otel-collector.otel:4317
      quarkus.http.port=8086

---
apiVersion: v1
kind: Service
metadata:
  name: rest-client-quickstart
  labels:
    app: rest-client-quickstart
spec:
  type: LoadBalancer
  selector:
    app: rest-client-quickstart
  ports:
    - name: http
      port: 8086
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-client-quickstart
    app.kubernetes.io/name: rest-client-quickstart
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: manifests
    app.kubernetes.io/created-by: admin
  name: rest-client-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-client-quickstart
  template:
    metadata:
      labels:
        app: rest-client-quickstart
    spec:
      containers:
        - name: rest-client-quickstart
          image: igoroschsimoes/rest-client-quickstart:v0.5
          resources: {}
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
          volumeMounts:
            - mountPath: /work/config
              name: config
      volumes:
        - name: config
          configMap:
            name: app-properties
