---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-json-quickstart-config
data:
  NATIVE: "0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: json-properties
data:
    application.properties: |
      quarkus.tls.trust-all=true
      quarkus.opentelemetry.tracer.exporter.otlp.endpoint=http://otel-collector.otel:4317
      quarkus.http.port=8087
---
apiVersion: v1
kind: Service
metadata:
  name: rest-json-quickstart
  labels:
    app: rest-json-quickstart
spec:
  selector:
    app: rest-json-quickstart
  ports:
    - name: http
      port: 8087
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-json-quickstart
    app.kubernetes.io/name: rest-json-quickstart
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: manifests
    app.kubernetes.io/created-by: admin
  name: rest-json-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-json-quickstart
  template:
    metadata:
      labels:
        app: rest-json-quickstart
    spec:
      containers:
        - name: rest-json-quickstart
          image: igoroschsimoes/rest-json-quickstart:v1
          imagePullPolicy: Always
          resources: {}
          envFrom:
            - configMapRef:
                name: rest-json-quickstart-config
          ports:
            - name: http
              containerPort: 8087
              protocol: TCP
          volumeMounts:
            - mountPath: /work/config
              name: config
      volumes:
        - name: config
          configMap:
            name: json-properties
